### ISSUE TITLE
Still get one unformatted log message from uvicorn

### ISSUE THREAD

**Issue by roblight** [MatthewScholefield/uvicorn-loguru-integration#1]
I have two files, `main.py` which contains the code as shown in the README, and another file `app.py` that contains a simple FastAPI application.  I execute the code with a bash script containing the line:

```
/usr/bin/env python3 "$APP_DIRNAME/src/main.py"
```

Which results with this output:

```
INFO:     Will watch for changes in these directories: ['/home/<redacted>']
2021-08-27 09:34:49.818 | INFO     | uvicorn.config:bind_socket:554 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2021-08-27 09:34:49.819 | INFO     | uvicorn.supervisors.basereload:startup:56 - Started reloader process [11158] using watchgod
```

I would have expected the line `INFO:     Will watch for changes in these directories: ['/home/<redacted>']` to be formatted as well.

Thank you!

**Comment by j4hangir** [comment]
Same here, still get `Exception in ASGI application` in regular format.

**Comment by MatthewScholefield** [comment]
Are you both using `reload=True` for live updates? I think it may be related to that.

**Comment by j4hangir** [comment]
> Are you both using `reload=True` for live updates? I think it may be related to that.

I confirm, any quick remedy?
